// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa8mFhV-APwEQ6WOw3RHAkWl2yyinKEvo',
    appId: '1:1020594764071:web:057fc604efd528f405d102',
    messagingSenderId: '1020594764071',
    projectId: 'flutter-yumly',
    authDomain: 'flutter-yumly.firebaseapp.com',
    storageBucket: 'flutter-yumly.appspot.com',
    measurementId: 'G-E4P0G8HXNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWDWY9tLBQOIu73GWh9ybko5apQ94PE_g',
    appId: '1:1020594764071:android:a2ba0e6267f31fed05d102',
    messagingSenderId: '1020594764071',
    projectId: 'flutter-yumly',
    storageBucket: 'flutter-yumly.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCilmHZKbK3svDaCdMPUn77pT_k_7Gpk5U',
    appId: '1:1020594764071:ios:53ed11d4991548d805d102',
    messagingSenderId: '1020594764071',
    projectId: 'flutter-yumly',
    storageBucket: 'flutter-yumly.appspot.com',
    iosBundleId: 'com.example.flutterProject2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCilmHZKbK3svDaCdMPUn77pT_k_7Gpk5U',
    appId: '1:1020594764071:ios:53ed11d4991548d805d102',
    messagingSenderId: '1020594764071',
    projectId: 'flutter-yumly',
    storageBucket: 'flutter-yumly.appspot.com',
    iosBundleId: 'com.example.flutterProject2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa8mFhV-APwEQ6WOw3RHAkWl2yyinKEvo',
    appId: '1:1020594764071:web:84844b4a745d411f05d102',
    messagingSenderId: '1020594764071',
    projectId: 'flutter-yumly',
    authDomain: 'flutter-yumly.firebaseapp.com',
    storageBucket: 'flutter-yumly.appspot.com',
    measurementId: 'G-GLDCX69X30',
  );

}